root = "/var/lib/containerd-rs"
state = "/run/containerd-rs"
cri_socket = "/run/containerd/containerd.sock"
stream_server_address = "127.0.0.1:10010"

[cri]
sandbox_image = "registry.k8s.io/pause:3.10"
systemd_cgroup = false
snapshotter = "overlayfs"
cni_conf_dir = "/etc/cni/net.d"
cni_bin_dir  = "/opt/cni/bin"
